services:
  - name: move-app
    type: web
    env: node
    plan: starter
    buildCommand: |
      cd frontend && yarn install --production=false && yarn build
      cd ../backend && yarn install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        fromGroup: move-app
      - key: JWT_SECRET
        fromGroup: move-app
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        fromGroup: move-app
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.crisp.chat; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.googleapis.com https://*.crisp.chat; img-src 'self' blob: data: https://*.googleapis.com https://*.gstatic.com https://*.crisp.chat; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://*.googleapis.com https://move-k987.onrender.com/api wss://*.crisp.chat; frame-src 'self' https://*.googleapis.com https://*.crisp.chat; worker-src 'self' blob:; child-src blob:; form-action 'self'; manifest-src 'self'; media-src 'self' https://*.crisp.chat; object-src 'none'; default-src 'self' https://*.crisp.chat wss://*.crisp.chat"
    healthCheckPath: /api/hello
    autoDeploy: true

  - name: move-frontend
    type: web
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://move-k987.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    routes:
      - type: rewrite
        source: /*
        destination: / 